name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x
          
      - name: Publish for ARM64
        run: |
          dotnet publish ./Il2CppDumper/Il2CppDumper.csproj \
            -r linux-arm64 \
            --self-contained true \
            --configuration Release \
            --output ./publish-arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Il2CppDumper-linux-arm64
          path: ./publish-arm64
